language: node_js
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH="$HOME/.yarn/bin:$PATH"
node_js:
  - 12.13.0
script:
  - npm test
  - npm run lint
  - npm run fmt:check
  - npm run build
