language: node_js
git:
  submodules: false
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH="$HOME/.yarn/bin:$PATH"
node_js:
  - 12.13.0
jobs:
  include:
    - stage: test
      name: "Tests, Linting, Formatting"
      script:
        - npm test
        - npm run lint
        - npm run fmt:check
    - if: branch != release
      stage: build
      name: "Run the build"
      script: npm run build
    - if: branch = release
      stage: deploy
      name: "Build and deploy to S3"
      script: npm run deploy