version: '3'
services:
  app:
    build: .
    container_name: hugo-course-publisher
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/usr/share/
    command: bash -c "git submodule update --init --recursive && npm install --prefix site/static/pdfjs && yarn install && npm start"
