version: '3'
services:
  app:
    user: ${MITODL_USER}
    build: .
    container_name: hugo-course-publisher
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/share/app
    command: bash -c "npm install && npm start"
