version: '3'

services:
  hugo:
    image: juristr/hugo-docker:latest
    working_dir: /srv/hugo
    volumes:
      - .:/srv/hugo
    command: "hugo server --bind 0.0.0.0 --templateMetrics"
    ports:
      - 1313:1313