version: '3'
services:
  app:
    build: .
    container_name: hugo-course-publisher
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/share/app
    command: bash -c "yarn install && npm start"
