version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    container_name: hugo-course-publisher
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/usr/share/
    command: bash -c "yarn install && npm run build:pdfjs && npm start"
