backend:
    name: git-gateway
    repo: hugo-courses/netlify-cms-testing
    branch: master
    identity_url: 'https://gotrue.d.odl.mit.edu'
    gateway_url: 'https://gitgateway.d.odl.mit.edu/18-06-linear-algebra-spring-2010'
    site_domain: 'https://trusting-snyder-003c24.netlify.com/'
    accept_roles:
        - admin
        - editor
identity_url: 'https://gotrue.d.odl.mit.edu'
publish_mode: editorial_workflow
media_folder: static/images/uploads
public_folder: /public/images/uploads
collections:
    -
        name: course-home
        label: 'Course Home'
        files:
            - {name: course-home-content, label: 'Course Home Content', file: _index.md, fields: [{label: Body, name: body, widget: markdown}]}
    -
        name: course-section
        label: 'Course Section'
        folder: sections
        create: true
        slug: '{{slug}}'
        fields:
            - {label: Title, name: title, widget: string}
            - {label: Body, name: body, widget: markdown}
