backend:
  name: git-gateway
  repo: hugo-courses/netlify-cms-testing
  branch: master
  identity_url: "http://localhost:8000/.netlify/identity"
  gateway_url: "http://localhost:8000/.netlify/git"
  site_domain: "http://localhost:8000"
  accept_roles:
    - admin
    - editor
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/public/images/uploads"
collections:
  - name: "course-section" # Used in routes, e.g., /admin/collections/blog
    label: "Course Section" # Used in the UI
    folder: "_sections" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}