backend:
  name: github
  repo: mitodl/hugo-course-publisher
  branch: netlify-testing
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/public/images/uploads"
collections:
  - name: "course-sections" # Used in routes, e.g., /admin/collections/blog
    label: "Course Sections" # Used in the UI
    folder: "content/_sections" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}