---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: site/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: site/content/courses
  label: Courses
  create: all
  match: "**/*"
upload_dir: site/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_VERSION=0.71.1
  - DANGEROUSLY_DISABLE_HOST_CHECK=true
  preview_output_directory: "../dist"
  install_dependencies_command: yarn install
  preview_docker_image: node:12.13.0
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -s site -p 3000 --bind 0.0.0.0
version: 0.71.1
