name: Scanning
on:
  schedule:
    - cron: '0 5 * * *'
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: refs/heads/master
      - name: OWASP ZAP Full Scan of RC
        uses: zaproxy/action-full-scan@master
        with:
          target: ${{ secrets.ZAP_RC_TARGET }}
          rules_file_name: '.zap/rules.tsv'
      - name: OWASP ZAP Full Scan of Production
        uses: zaproxy/action-full-scan@master
        with:
          target: ${{ secrets.ZAP_PROD_TARGET }}
          rules_file_name: '.zap/rules.tsv'
